version: '3'
 
services:
  tor-browser:
    build: .
    image: desktopcontainers/tor-browser
    network_mode: bridge
    restart: always
    shm_size: "2g"
    environment:
      SERVER_NAME: localhost

      VNC_SCREEN_DEPTH: 24

      #ENABLE_SUDO: enable
      #ENABLE_KIOSK: enable
#    volumes:
#      - ./certs:/certs
    ports:
      - "22"
#      - "8080:80"
#      - "4443:443"
#      - "5900:5900"
